= Documentation technique Version 1
:toc:
:toc-title: Sommaire

Créé par : Équipe 1B1

== I. Présentation de l'application
[.text-justify]
La banque DailyBank souhaite développer une application JAVA-Oracle de gestion des comptes clients pour remplacer plusieurs outils obsolètes. Ce développement s’inscrit dans le cadre de la restructuration de ses services bancaires et l’application sera déployée dans les 100 agences que compte son réseau. L’objectif est d’ajouter des fonctionnalités à cette première version de l’application.

== II. Organisation
Baelen Julie -> Créditer, débiter + CRUD + Documentation utilisateur.



== II. Architecture



== III. Description des fonctionnalités

=== 1. Créditer/ débiter, par Julie Baelen

Premierement, je me suis essentiellement inspirée des fonctions "débiter", en changeant bien sur les noms des variables et leurs actions. De plus, j'ai ajouté dans la base de données la fonction créditer, qui fonctionne comme débiter mais sans découvert autorisé et en additionant. J'ai donc créé une dependance sous oracle du nom de "créditer".
