= Documentation technique Version 1
:toc:
:toc-title: Sommaire

Créé par : Équipe 1B1

== I. Présentation de l'application
[.text-justify]
La banque DailyBank souhaite développer une application JAVA-Oracle de gestion des comptes clients pour remplacer plusieurs outils obsolètes. Ce développement s’inscrit dans le cadre de la restructuration de ses services bancaires et l’application sera déployée dans les 100 agences que compte son réseau. L’objectif est d’ajouter des fonctionnalités à cette première version de l’application.



== II. Organisation
Julie BAELEN -> Créditer / Débiter +
Guilherme SAMPAIO -> Créer un compte +
Bastien RECORD -> Clôturer un compte et Virement de compte à compte



== II. Architecture



== III. Description des fonctionnalités
=== 1. Fonctionnalité Guichetier
==== 1.1. Modifier informations client


==== 1.2 Créer un nouveau client


==== 1.3. Consulter un compte



==== 1.4. Débiter un compte




=== 1. Créditer / Débiter (JB)

Premierement, je me suis essentiellement inspirée des fonctions "débiter", en changeant bien sur les noms des variables et leurs actions. De plus, j'ai ajouté dans la base de données la fonction créditer, qui fonctionne comme débiter mais sans découvert autorisé et en additionant. J'ai donc créé une dependance sous oracle du nom de "créditer".


