= Cahier De Tests - DailyBankApp V2
:toc:
:toc-title: Sommaire

:Entreprise: DailyBank
:Equipe: 1B1

Créé par : Groupe 1B1

== I. Introduction
=== 1. Objet :
[.text-justify]
Ce document a été produit dans le cadre d'un projet d'élaboration d'une application bancaire pour permettre d'élaborer différents tests de l'application pour montrer son bon fonctionnement.



== II. Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Une base de données installée (référence document technique).
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Un exécutable jar (application dans laquelle les tests doivent être effectués)


=== 1. Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases qui sont spécifiés dans la *documentation technique*.


=== 2. Environnement de test :
[.text-justify]
Ordinateur sous Windows ou OS équivalent.



== III. Cas de test :
=== 1. Fonctionnalités des guichetiers :
==== 1.1 Gestion des clients V0 :

|====

>|Cas de test 4+|Test-01-01-01
>|Titre 4+|Création d'un nouveau client
>|Objectif 4+| Vérifier qu'il est possible de créer un nouveau client
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur le bouton "Nouveau client". ^|La fenêtre de création des clients s'ouvre. ^|aucune ^|OK
^|All_G_C.2 ^|Compléter les champs spécifiés et valider. ^|Un nouveau client est créé. ^|Tous les champs doivent être remplis ^|OK
5+|
5+|Commentaire : Un nouveau client est créé et enregistré dans la Base de données. Il est affiché dans la liste des clients.

|====

|====

>|Cas de test 4+|Test-01-01-02
>|Titre 4+|Modification d'un client
>|Objectif 4+| Vérifier qu'il est possible de modifier un client
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.3 ^|Cliquer sur le bouton "Modifier client". ^|La fenêtre de modification des données du clients s'ouvre. ^|Le client est sélectionné ^|OK
^|All_G_C.4 ^|Modifier les champs souhaités et confirmer. ^|Retour sur les informations du client. Le client est modifié. ^|La fenêtre "Modifier client" est active ^|OK
^|All_G_C.5 ^|Modifier les champs souhaités et annuler. ^|Retour sur les informations du client. Le client est inchangé. ^|La fenêtre "Modifier client" est active ^|OK
5+|
5+|Commentaire : La modification des clients affiche un fenêtre avec les informations déjà inscrites. L'ID et rendre le client actif ou inactif est imposible à changer.

|====


==== 1.2 Gestion des comptes bancaires (GS et BR):

|====

>|Cas de test 4+|Test-01-02-01
>|Titre 4+|Consultation d'un compte
>|Objectif 4+| Vérifier qu'il est possible de consulter un compte
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Comptes client". ^|La page des comptes du client s’affiche. ^|Un client actif est sélectionné ^|OK
^|All_G_CB.2 ^|Sélectionner le bouton "Voir opérations". ^|La page des opérations du compte s’affiche. ^|Un compte actif est sélectionné ^|OK
5+|
5+|Commentaire : La consultation des comptes d'un client permet de voir l'historique des différentes opérations effectuées sur ce compte.

|====

|====

>|Cas de test 4+|Test-01-02-02
>|Titre 4+|Créer un compte
>|Objectif 4+|Vérifier qu'il est possible de créer un compte
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Nouveau compte". ^|La page de gestion d'un compte s’affiche. ^|aucune ^|OK
^|All_G_CB.2 ^|Remplir les champs et cliquer sur "Ajouter" ^|Le compte est ajouter et s'affiche dans la liste des comptes clients ^|Les champs doivent être corrects ^|OK
^|All_G_CB.3 ^|Remplir les champs et cliquer sur "Annuler" ^|La liste des comptes n'est pas modifiée ^|aucune ^|OK
5+|
5+|Commentaire : Seulement les champs découvert autorisé et solde sont à remplir. Les autres champs s'implémentent automatiquement.

|====

|====

>|Cas de test 4+|Test-01-02-03
>|Titre 4+|Clôturer un compte
>|Objectif 4+|Vérifier qu'il est possible de clôturer un compte
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Clôturer compte". ^|Le compte devient clôturé à la place d'ouvert ^|Un compte actif est sélectionné ^|OK
5+|
5+|Commentaire : Lorsqu'un compte est clôturé il est impossible d'effectuer des opérations.

|====

|====

>|Cas de test 4+|Test-01-02-04
>|Titre 4+|Générer un relevé mensuel d'un compte en pdf
>|Objectif 4+|Vérifier qu'il est possible de générer un relevé mensuel (en pdf)
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Relevé de compte". ^|Si aucune fenêtre ne s'affiche alors se rendre à l'emplacement de notre application et ouvrir le fichier pdf générer correspondant. Un tableau est représenté avec les différentes actions effectuées ce mois-ci. ^|Un compte clôturer ou non est ouvert avec les différentes actions (toutes dates confondu) sous formes de listes. ^|OK
^|All_G_CB.2 ^|Cliquer sur le bouton "Relevé de compte". ^|Une fenêtre s'ouvre avec un message d'erreur "impossible de générer le relevé de compte". Aucun fichier pdf n'est alors créer dans notre espace de document. ^|Un compte clôturer ou non est ouvert mais la liste des différentes opérations est vide. ^|OK
^|All_G_CB.3 ^|Cliquer sur le bouton "Relevé de compte". ^|Une fenêtre s'ouvre avec un message d'erreur "impossible de générer le relevé de compte". Aucun fichier pdf n'est alors créer dans notre espace de document. ^|Un compte clôturer ou non est ouvert mais la liste des différentes opérations contient différentes opérations ne correspondant pas au mois et année actuel (localhost). ^|OK
5+|
5+|Commentaire : Lorsqu'un compte n'a aucune opération alors le relevé mensuel n'est pas généré. Pour générer le relevé mensuel, seul les opérations effectuées le même mois et année (localhost) que l'action de générer le relevé sont alors inscrites dans la pdf.

|====

==== 1.3 Gestion des opérations (JB et BR) :

|====

>|Cas de test 4+|Test-01-03-01
>|Titre 4+|Débiter un compte
>|Objectif 4+| Vérifier qu'il est possible de débiter un compte
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Enregistrer Débit". ^|La page des débits du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros ^|OK
^|All_G_COP.3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est -50 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros, le découvert autorisé est de -100 euros. ^|OK
^|All_G_COP.4  ^|Rentrer un montant 250 dans le champ "Montant". ^|Blocage ! + pop-up ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros. ^|OK
5+|
5+|Commentaire : L'opération est possible seulement quand un compte est actif. Le montant à débiter ne doit pas dépasser le découvert autorisé lors du débit au solde.

|====

|====

>|Cas de test 4+|Test-01-03-02
>|Titre 4+|Créditer un compte
>|Objectif 4+| Vérifier qu'il est possible de créditer un compte
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Enregistrer Crédit". ^|La page des débit du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +150euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros ^|OK
^|All_G_COP.3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est -50 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de -200 euros ^|OK
5+|
5+|Commentaire : Le montant à créditer doit être positif pour que le crédit soit effectué.

|====

|====

>|Cas de test 4+|Test-01-03-03
>|Titre 4+|Effectuer un virement de compte à compte
>|Objectif 4+| Vérifier qu'il est possible de faire un virement vers un autre compte
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Virement compte à compte". ^|La page des virements du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant" et sélectionner le compte destinataire dans la liste déroulante ^|Le nouveau solde est +50euros et le solde du compte destinataire est de +250euros. ^| Le compte sélectionné a un solde de +100 euros et le compte destinataire à un solde de +200 ^|OK
5+|Commentaire : Le virement est effectué seulement entre deux comptes non clôturer d'un client.

|====

==== 1.4 Gestion des prélèvements automatiques (GS):

|====

>|Cas de test 4+|Test-01-04-01
>|Titre 4+|Ouvrir la fenêtre
>|Objectif 4+| Faire apparaître les prélèvements automatiques du compte selectionné
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_RP.1 ^|Cliquer sur le bouton "Voir prél. auto.". ^|La fenêtre de gestion des prélèvements s'ouvre. ^|Avoir sélectionné un compte d'un client ^|OK
5+|
5+|Commentaire : Le bouton "Voir prél. auto." s'active uniquement après sélectionner un compte d'un client et les prélèvements affichés correspondent aux prélèvements de ce compte uniquement, il n'y aura aucun s'il n'y a aucun prélèvement dans le compte.

|====

|====

>|Cas de test 4+|Test-01-04-02
>|Titre 4+|Rechercher un prélèvement spécifique
>|Objectif 4+| Faire apparaître uniquement le prélèvement recherché
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_RP.1b ^|Saisir l'identifiant du prélèvement dans le champ "Numéro" et cliquer sur "Rechercher". ^|Seul le prélèvement recherché reste. ^|Le prélèvement recherché existe et il correspond au compte sélectionné ^|OK
5+|
5+|Commentaire : Si le champ "Numéro" est vide, on obtiendra tous les prélèvements automatiques du compte et si l'identifiant saisi n'existe ou ne correspond pas avec le compte sélectionné la liste sera vide.

|====

|====

>|Cas de test 4+|Test-01-04-03
>|Titre 4+|Modifier un prélèvement 
>|Objectif 4+| Modifier les informations d'un prélèvemnt
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_MP.1 ^|Cliquer sur "Modifier prél. auto." ^|La fenêtre de modification apparaît ^|Un prélèvement a été sélectionné ^|OK
^|All_G_MP.2 ^|Saisir le nouveau montant et cliquer sur "Modifier" ^|Le montant du prélèvement est modifié et enregistré dans la base de données ^|Le montant saisi est un nombre supérieur à 0 ^|OK
^|All_G_MP.3 ^|Saisir la nouvelle date récurrente et cliquer sur "Modifier" ^|La date récurrente du prélèvement est modifiée et enregistrée dans la base de données ^|La date récurrente saisie est un nombre supérieur à 0 et inférieur à 28(à cause du mois de février) ^|OK
^|All_G_MP.4 ^|Saisir le nouveau bénéficiaire et cliquer sur "Modifier" ^|Le bénéficiaire du prélèvement est modifié et enregistré dans la base de données ^|Le bénéficiaire a été saisi ^|OK
5+|
5+|Commentaire : Le bouton "Modifier prél. auto." s'active uniquement si un prélèvement automatique a été sélectionné.

|====

|====

>|Cas de test 4+|Test-01-04-04
>|Titre 4+|Ajouter des prélèvements
>|Objectif 4+|Enregistrer un nouveau prélèvement dans la base de données
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_CP.1 ^|Cliquer sur le bouton "Nouveau prél. auto." ^|Une fenêtre s'ouvre pour saisir les informations du nouveau prélèvement ^|Aucune ^|OK
^|C_G_CP.2 ^|Saisir les informations et cliquer sur "Ajouter" ^|Le prélèvement est enregistré dans la base de données et apparaît dans la liste des prélèvements et la fenêtre se ferme ^|Avoir ouvert la fenêtre de création et saisi toutes les informations demandées ^|OK
^|C_G_CP.3 ^|Saisir toutes les informations sauf "Montant" ^|Une fenêtre d'erreur apparaît indiquant "Saisissez un montant valide(un nombre)" ^|Aucune ^|OK
^|C_G_CP.4 ^|Saisir toutes les informations mais "Montant" est un nombre inférieur ou égal à 0 ^|Une fenêtre d'erreur apparaît indiquant "Saisissez un montant valide(supérieur à 0)" ^|Aucune ^|OK
^|C_G_CP.5 ^|Saisir toutes les informations sauf "Date récurrente" ^|Une fenêtre d'erreur apparaît indiquant "Saisissez une date récurrente valide (un nombre)" ^|Aucune ^|OK
^|C_G_CP.6 ^|Saisir toutes les informations mais "Date récurrente"  est un nombre qui n'est pas compris entre 1 et 28 ^|Une fenêtre d'erreur apparaît indiquant "Saisissez une date récurrente valide (de 1 à 28)" ^|Aucune ^|OK
^|C_G_CP.7 ^|Saisir toutes les informations sauf "Bénéficiaire" ^|Une fenêtre d'erreur apparaît indiquant "Le bénéficiaire ne doit pas être vide" ^|Aucune ^|OK
5+|
5+|Commentaire : 

|====

|====

>|Cas de test 4+|Test-01-04-05
>|Titre 4+|Supprimer des prélèvements
>|Objectif 4+|Supprimer un prélèvement de la base de données
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_DP.1 ^|Cliquer sur le bouton "Supprimer prél. auto." ^|Une fenêtre s'ouvre pour demander la confirmation de la suppression du compte ^|Un prélèvement a été sélectionné ^|OK
^|C_G_DP.2 ^|Cliquer sur "Accepter" ^|Le prélèvement est supprimé de la base de données, disparaît de la liste des prélèvements et la fenêtre se ferme ^|Aucune ^|OK
^|C_G_DP.3 ^|Cliquer sur "Annuler" ^|Le prélèvement reste dans la base de données et la fenêtre se ferme ^|Aucune ^|OK
5+|
5+|Commentaire : Le bouton "Supprimer prél. auto." s'active uniquement après avoir sélectionné un prélèvement.

|====



=== 2. Fonctionnalités des chefs d'agence :
[.text-justify]
Les chefs d'agence ont accès aux mêmes fonctionnalités que les guichetiers, ainsi que d'autres qui leur sont réservées.


==== 2.1 Gestion des clients V0 :

|====

>|Cas de test 4+|Test-02-01-01
>|Titre 4+|Rendre inactif un client
>|Objectif 4+|Vérifier qu'il est possible de rendre un client inactif
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1 ^|Sélectionner le bouton "Inactif" et confirmer. ^|Le client est devenu inactif ^|Un client actif est sélectionné ^|OK
5+|
5+|Commentaire : Rendre un client inactif n'empêche pas de faire des opérations sur ses comptes.

|====

==== 2.2 Gestion des employés (GS) :

|====

>|Cas de test 4+|Test-02-02-01
>|Titre 4+|Vérifier qu'on peut rechercher un employé par son id
>|Objectif 4+|Obtenir un employé spécifique en saisissant uniquement son id
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_RE.1 ^|Saisir l'idEmploye désiré dans le champ "Numéro" ^|On trouve l'employé associé à l'identifiant saisi ^|L'employé associé à l'identifiant existe ^|OK
^|C_G_RE.2 ^|Saisir l'idEmploye d'un employé ^|On ne trouve aucun employé ^|L'employé associé à l'identifiant saisi n'existe pas ^|OK
5+|
5+|Commentaire : Si l'employé n'existe pas, la liste d'employés sera vide, parce qu'on ne trouve aucun employé.

|====

|====

>|Cas de test 4+|Test-02-02-02
>|Titre 4+|Vérifier qu'on peut rechercher un employé par son nom et/ou prénom
>|Objectif 4+|Obtenir les employés en fonction de son nom et/ou son prénom
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_RE.3 ^|Saisir le nom de l'employé désiré dans le champ "Nom" et cliquer sur "Rechercher" ^|On trouve des employés ^|Il y a des employés avec ce nom ^|OK
^|C_G_RE.4 ^|Saisir le prénom de l'employé désiré dans le champ "Prénom" et cliquer sur "Rechercher" ^|On trouve des employés ^|Il y a des employés avec ce prénom ^|OK
^|C_G_RE.5 ^|Saisir le nom/prénom de l'employé désiré dans les champs dédiés et cliquer sur "Rechercher" ^|On trouve des employés ^|Il y a des employés avec ces noms/prénoms ^|OK
5+|
5+|Commentaire : S'il n'y a aucun employé avec ces noms/prénoms, la liste sera vide. On peut rechercher par seulement le nom, seulement le prénom ou le nom ET le prénom.

|====

|====

>|Cas de test 4+|Test-02-02-03
>|Titre 4+|Voir tous les employés
>|Objectif 4+|Obtenir une liste avec tous les employés de l'agence
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_RE.6 ^|Cliquer sur le bouton "Rechercher" ^|On trouve tous les employés de l'agence ^|Les champs de texte de recherche sont vides ^|OK
5+|
5+|Commentaire : Si un des champs de texte de recherche n'est pas vide, on n'obtiendra que les employés qui correspondent à la recherche.

|====

|====

>|Cas de test 4+|Test-02-02-04
>|Titre 4+|Modifier les employés
>|Objectif 4+|Faire des modifications sur les employés
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_UE.1 ^|Cliquer sur le bouton "Modifier" ^|Une fenêtre s'ouvre pour modifier les informations de l'employé ^|Avoir sélectionné un employé ^|OK
^|C_G_UE.2 ^|Modifier les informations et cliquer sur "Modifier" ^|Les informations de l'employé ont changé dans la base de données et dans la liste et la fenêtre se ferme ^|Avoir ouvert la fenêtre de modification ^|OK
^|C_G_UE.3 ^|Modifier les informations et cliquer sur "Annuler" ^|La fenêtre se ferme et aucune modification est sauvegardée ^| Avoir ouvert la fenêtre de modification ^|OK
5+|
5+|Commentaire : Le bouton de modification s'active uniquement si on a sélectionné un employé.

|====

|====

>|Cas de test 4+|Test-02-02-05
>|Titre 4+|Ajouter des employés
>|Objectif 4+|Enregistrer un nouveau employé dans la base de données
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_CE.1 ^|Cliquer sur le bouton "Nouveau employé" ^|Une fenêtre s'ouvre pour saisir les informations du nouveau employé ^|Aucune ^|OK
^|C_G_CE.2 ^|Saisir les informations et cliquer sur "Ajouter" ^|L'employé est enregistré dans la base de données et apparaît dans la liste des employés et la fenêtre se ferme ^|Avoir ouvert la fenêtre de modification et saisi toutes les informations demandées ^|OK
^|C_G_CE.3 ^|Saisir toutes les informations sauf "Nom" ^|Une fenêtre d'erreur apparaît indiquant "Le nom ne doit pas être vide" ^|Aucune ^|OK
^|C_G_CE.4 ^|Saisir toutes les informations sauf "Prénom" ^|Une fenêtre d'erreur apparaît indiquant "Le prénom ne doit pas être vide" ^|Aucune ^|OK
^|C_G_CE.5 ^|Saisir toutes les informations sauf "Droits accès" ^|Une fenêtre d'erreur apparaît indiquant "Les droits d'accès ne doivent pas être vides" ^|Aucune ^|OK
^|C_G_CE.6 ^|Saisir toutes les informations sauf "Login" ^|Une fenêtre d'erreur apparaît indiquant "Le login ne doit pas être vide" ^|Aucune ^|OK
^|C_G_CE.7 ^|Saisir toutes les informations sauf "Mot de Passe" ^|Une fenêtre d'erreur apparaît indiquant "Le mot de passe ne doit pas être vide" ^|Aucune ^|OK
^|C_G_CE.8 ^|Saisir les informations et cliquer sur "Annuler" ^|La fenêtre se ferme et l'employé n'est pas sauvegaardé ^| Avoir ouvert la fenêtre de modification ^|OK
5+|
5+|Commentaire : 

|====

|====

>|Cas de test 4+|Test-02-02-06
>|Titre 4+|Supprimer un employé
>|Objectif 4+|Supprimer un employé de la base de données
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_UE.1 ^|Cliquer sur le bouton "Supprimer employé" ^|Une fenêtre s'ouvre pour demander la confirmation de la suppression de l'employé ^|Avoir sélectionné un employé ^|OK
^|C_G_UE.2 ^|Cliquer sur "Accepter" ^|L'employé est supprimé de la base de données ^|Aucune ^|OK
^|C_G_UE.3 ^|Cliquer sur "Annuler" ^|La fenêtre se ferme et l'employé reste dans la base de données ^|Aucune ^|OK
5+|
5+|Commentaire : Le bouton de suppression s'active uniquement si on a sélectionné un employé.

|====



==== 2.3 Gestion des opérations (JB) :

|====

>|Cas de test 4+|Test-02-03-01
>|Titre 4+|Débit Exceptionnel sur un compte
>|Objectif 4+| Vérifier qu'il est possible de débiter un compte sans prendre en compte le découvert autorisé
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_COP.1 ^|Cliquer sur le bouton "Débit Exceptionnel". ^|La page des débit exceptionnel du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|C_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros ^|OK
^|C_G_COP.3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est -50 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros, le découvert autorisé est de -100 euros. ^|OK
^|C_G_COP.4  ^|Rentrer un montant 250 dans le champ "Montant". ^|Le nouveau solde est -150 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date  | Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros. Mais il n'impact pas sur l'opération ^|OK
5+|
5+|Commentaire : L'opération est possible seulement quand un compte est actif. Le montant à débiter peut dépasser le découvert autorisé lors du débit au solde.

|====
