= Cahier De Tests - DailyBankApp V2
:toc:
:toc-title: Sommaire

:Entreprise: DailyBank
:Equipe: 1B1

Créé par : Groupe 1B1

== I. Introduction
=== 1. Objet :
[.text-justify]
Ce document a été produit dans le cadre d'un projet d'élaboration d'une application bancaire pour permettre d'élaborer différents tests de l'applications pour montrer son bon fonctionnement.



== II. Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Une base de données installée (référence document technique).
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Un exécutable jar (application dans laquelle les tests doivent être effectués)


=== 1. Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases sont spécifiés dans la *documentation technique*.


=== 2. Environnement de test :
[.text-justify]
Ordinateur sous Windows ou OS équivalent.



== III. Cas de test :
=== 1. Fonctionnalités des guichetiers :
==== 1.1 Gestion des clients V0 :

|====

>|Cas de test 4+|Test-01-01-01
>|Titre 4+|Création d'un nouveau client
>|Objectif 4+| Vérifier qu'il est possible de créer un nouveau client
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur le bouton "Nouveau client". ^|La fenêtre de création des clients s'ouvre. ^|aucune ^|OK
^|All_G_C.2 ^|Compléter les champs spécifiés et valider. ^|Un nouveau client est créé. ^|Tous les champs doivent être remplis ^|OK
5+|
5+|Commentaire : Un nouveau client est créé et enregistré dans la Base de données. Il est afficher dans la liste des clients.

|====

|====

>|Cas de test 4+|Test-01-01-02
>|Titre 4+|Modification d'un client
>|Objectif 4+| Vérifier qu'il est possible de modifier un client
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.3 ^|Cliquer sur le bouton "Modifier client". ^|La fenêtre de modification des données du clients s'ouvre. ^|Le client est sélectionné ^|OK
^|All_G_C.4 ^|Modifier les champs souhaités et confirmer. ^|Retour sur les informations du client. Le client est modifié. ^|La fenêtre modifier client est active ^|OK
^|All_G_C.5 ^|Modifier les champs souhaités et annuler. ^|Retour sur les informations du client. Le client est inchangé. ^|La fenêtre modifier client est active ^|OK
5+|
5+|Commentaire : La modification des clients affiche un fenêtre avec les informations déjà inscrites. L'ID et rendre le client actif ou inactif est imposible à changer.

|====


==== 1.2 Gestion des comptes bancaires (GS et BR):

|====

>|Cas de test 4+|Test-01-02-01
>|Titre 4+|Consultation d'un compte
>|Objectif 4+| Vérifier qu'il est possible de consulter un compte
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Comptes client". ^|La page des comptes du client s’affiche. ^|Un client actif est sélectionné ^|OK
^|All_G_CB.2 ^|Sélectionner le bouton "Voir opérations". ^|La page des opérations du compte s’affiche. ^|Un compte actif est sélectionné ^|OK
5+|
5+|Commentaire : La consultation des comptes d'un client permet de voir l'historique des différentes opérations effectuées sur ce compte.

|====

|====

>|Cas de test 4+|Test-01-02-02
>|Titre 4+|Créer un compte
>|Objectif 4+|Vérifier qu'il est possible de créer un compte
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Nouveau compte". ^|La page de gestion d'un compte s’affiche. ^|aucune ^|OK
^|All_G_CB.2 ^|Remplir les champs et cliquer sur ajouter ^|Le compte est ajouter et s'affiche dans la liste des comtpes clients ^|Les champs doivent être correct ^|OK
^|All_G_CB.3 ^|Remplir les champs et cliquer sur annuler ^|La liste des comtpes n'est pas modifiée ^|aucune ^|OK
5+|
5+|Commentaire : Seulement les champs découvert autorisé et solde sont à remplir. Les autres champs s'implémentent automatiquement.

|====

|====

>|Cas de test 4+|Test-01-02-03
>|Titre 4+|Clôturer un compte
>|Objectif 4+|Vérifier qu'il est possible de clôturer un compte
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Clôturer compte". ^|Le compte devient clôturer à la place d'ouvert ^|Un compte actif est sélectionné ^|OK
5+|
5+|Commentaire : Lorsqu'un compte est clôturé il est impossible d'effectuer des opérations.

|====


==== 1.3 Gestion des opérations (JB et BR) :

|====

>|Cas de test 4+|Test-01-03-01
>|Titre 4+|Débiter un compte
>|Objectif 4+| Vérifier qu'il est possible de débiter un compte
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Enregistrer Débit". ^|La page des débit du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros ^|OK
^|All_G_COP.3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est -50 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros, le découvert autorisé est de -100 euros. ^|OK
^|All_G_COP.4  ^|Rentrer un montant 250 dans le champ "Montant". ^|Blocage ! + pop-up ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros. ^|OK
5+|
5+|Commentaire : L'opération est possible seulement quand un compte est actif. Le montant à débiter ne doit pas dépasser le découvert autorisé lors du débit au solde.

|====

|====

>|Cas de test 4+|Test-01-03-02
>|Titre 4+|Créditer un compte
>|Objectif 4+| Vérifier qu'il est possible de créditer un compte
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Enregistrer Crédit". ^|La page des débit du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +150euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros ^|OK
^|All_G_COP.3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est -50 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de -200 euros ^|OK
5+|
5+|Commentaire : Le montant à créditer doit être positif pour que le crédit soit effectué.

|====

|====

>|Cas de test 4+|Test-01-03-03
>|Titre 4+|Effectuer un virement de compte à compte
>|Objectif 4+| Vérifier qu'il est possible de faire un virement vers un autre compte
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Virement compte à compte". ^|La page des virements du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant" et sélectionner le compte destinataire dans la liste déroulante ^|Le nouveau solde est +50euros et le solde du compte destinataire est de +250euros. ^| Le compte sélectionné a un solde de +100 euros et le compte destinataire à un solde de +200 ^|OK
5+|Commentaire : Le virement est effectué seulement entre deux comptes non clôturer d'un client.

|====

=== 2. Fonctionnalités des chefs d'agence :
[.text-justify]
Les chefs d'agence ont accès aux mêmes fonctionnalités que les guichetiers, ainsi que d'autres qui leur sont réservées.


==== 2.1 Gestion des clients V0 :

|====

>|Cas de test 4+|Test-02-01-01
>|Titre 4+|Rendre inactif un client
>|Objectif 4+|Vérifier qu'il est possible de rendre un client inactif
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1 ^|Sélectionner le bouton "Inactif" et confirmer. ^|Le client est devenue inactif ^|Un client actif est sélectionné ^|OK
5+|
5+|Commentaire : Rendre un client inactif n'empêche pas de faire des opérations sur ses comptes.

|====

==== 2.2 Gestion des employés (GS) :

*Manque de temps pour la Version 1*


==== 2.3 Gestion des opérations (JB) :

|====

>|Cas de test 4+|Test-02-03-01
>|Titre 4+|Débit Exceptionnel sur un compte
>|Objectif 4+| Vérifier qu'il est possible de débiter un compte sans prendre en compte le découvert autorisé
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Débit Exceptionnel". ^|La page des débit exceptionnel du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros ^|OK
^|All_G_COP.3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est -50 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros, le découvert autorisé est de -100 euros. ^|OK
^|All_G_COP.4  ^|Rentrer un montant 250 dans le champ "Montant". ^|Le nouveau solde est -150 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date  | Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros. Mais il n'impact pas sur l'opération ^|OK
5+|
5+|Commentaire : L'opération est possible seulement quand un compte est actif. Le montant à débiter peut dépasser le découvert autorisé lors du débit au solde.

|====
