= Cahier des charges Version 2
:toc:
:toc-title: Sommaire

Date : 16/05/2023 +
Créé par : Équipe 1B1
Créé pour : Directeur de la banque DailyBank

== I. Présentation
=== 1. Contexte
[.text-justify]
La banque DailyBank souhaite développer une application JAVA-Oracle de gestion des comptes clients pour remplacer plusieurs outils obsolètes. Ce développement s’inscrit dans le cadre de la restructuration de ses services bancaires et l’application sera déployée dans les 100 agences que compte son réseau.


=== 2. Objectifs
[.text-justify]
L’application doit permettre de gérer des comptes bancaires de dépôt pour des clients préalablement créés. Elle devra permettre de débiter, créditer un compte soit par virement c’est à dire un échange d’argent entre deux comptes distincts mais domiciliés dans le réseau bancaire, soit par une personne physique se présentant devant un guichet.



== III. Analyse de l'existant
[.text-justify]
Un application JAVA-Oracle déjà existante possède différentes options comme : modifier les informations d'un clients, créer un nouveau client, consulter un compte, débiter un compte et rendre inactif un client.



== IV. Description fonctionnelle des besoins

Fonction : Créditer / Débiter un compte::
    Objectif : Permettre d'effectuer des débits et des dépôts sur un compte +
    Description : Cette action est réalisable par un guichetier

Fonction : Créer un compte::
    Objectif : Permettre d'ajoouter un compte à un utilisateur +
    Description : Cette action est réalisable par un guichetier

Fonction : Effectuer un virement de compte à compte::
    Objectif : Permettre de faire un virement d'un compte vers un autre +
    Description : Cette action est réalisable par un guichetier

Fonction : Clôturer un compte::
    Objectif : Permettre de fermer un compte existant +
    Description : Cette action est réalisable par un guichetier

Fonction : Gérer les employés::
    Objectif : Permettre de faire le CRUD sur tous types d'employés +
    Description : Cette action est réalisable par un chef d'agence



== V. Analyse des contraintes

Il y a différents types de contraintes, comme les contraintes techniques ou organisationnelles.

Les contraintes techniques sont:: 
    - Certaines fonctionnalitées ne fonctionnent que pour un certain rôle +
    - Il faut savoir relier la base de données avec le code java +
    - Modifier le javafx 
Les contraintes organisationnelles sont::
    - La version doit être livrée le 17 mai +
    - La répartition des rôles de l'équipe +
    - Gestion du git
