= Cahier des charges - DailyBank Version 2
:toc:
:toc-title: Sommaire

Date : 16/05/2023 +
Créé par : Équipe 1B1
Participants : Guilherme SAMPAIO, Julie BAELEN et Bastien RECORD +
Créé pour : Directeur de la banque DailyBank

== I. Présentation
=== 1. Contexte
[.text-justify]
Pour s’adapter aux exigences d’instantanéité de leurs clients, les banques françaises ont accentué leurs efforts de restructuration et leurs investissements dans le digital. Des chantiers longs et coûteux. Par exemple, la Banque Postale a indiqué que sa banque mobile baptisée Ma French Bank sera disponible dans les bureaux de Poste au printemps 2019. Mais les banques ne se contentent pas de créer des offres alternatives : elles rénovent aussi en profondeur leurs services de banque au quotidien. +
Au sein des réseaux de banque de détail, cela se traduit par des investissements majeurs dans la modernisation des outils de bureautique des guichetiers, et dans la robotisation des tâches automatisables. Un exercice qui s’accompagne de restructurations et, dans certains cas, d’une refonte du réseau.

=== 2. Objectifs
[.text-justify]
La banque DailyBank souhaite développer une application JAVA-Oracle de gestion des comptes clients pour remplacer plusieurs outils obsolètes. Ce développement s’inscrit dans le cadre de la restructuration de ses services bancaires et l’application sera déployée dans les 100 agences que compte son réseau. +
L’application doit permettre de gérer des comptes bancaires de dépôt pour des clients préalablement créés. Elle devra permettre de débiter, créditer un compte soit par virement c’est à dire un échange d’argent entre deux comptes distincts mais domiciliés dans le réseau bancaire, soit par une personne physique se présentant devant un guichet.



== III. Analyse de l'existant
[.text-justify]
Un application JAVA-Oracle déjà existante possède différentes options. +
Une application est déjà fournis. Elle est organisée en plusieurs parties. La première partie est la page de connexion à la banque à l'aide de nos identifiants. Après la connexion l'application se sépare en deux partie : la partie de gestions des clients et la partie de gestion des employés. Dans la gestion des clients, il est possible d'ajouter des clients et de gérer leur comptes en y faisant des dépôts ou des retraits, ajouter un nouveau compte et clôturer un compte. Dans la partie gestion des employés, il est possible de consulter les employés, de modifier un employé, d'ajouter un employé et de supprimer un employé. +
Pour l'utilisation de cette application, il existe deux rôles : les guichetiers et les chefs d'agences. +
Un guichetier a accès à la gestion des clients et de leurs comptes. Cependant, il ne peut pas rendre innactif un client. +
Un chef d'agence a les mêmes fonctionnalités qu'un guichetier mais il peut aussi accèder à la gestion des employés et rendre inactif un client.



== IV. Description fonctionnelle des besoins

Fonction : Créditer / Débiter un compte::
    Objectif : Permettre d'effectuer des débits et des dépôts sur un compte +
    Description : Cette action est réalisable par un guichetier

Fonction : Créer un compte::
    Objectif : Permettre d'ajoouter un compte à un utilisateur +
    Description : Cette action est réalisable par un guichetier

Fonction : Effectuer un virement de compte à compte::
    Objectif : Permettre de faire un virement d'un compte vers un autre +
    Description : Cette action est réalisable par un guichetier

Fonction : Clôturer un compte::
    Objectif : Permettre de fermer un compte existant +
    Description : Cette action est réalisable par un guichetier

Fonction : Gérer les employés::
    Objectif : Permettre de faire le CRUD sur tous types d'employés +
    Description : Cette action est réalisable par un chef d'agence



== V. Analyse des contraintes

Il y a différents types de contraintes, comme les contraintes techniques ou organisationnelles.

Les contraintes techniques sont:: 
    - Certaines fonctionnalitées ne fonctionnent que pour un certain rôle +
    - Il faut savoir relier la base de données avec le code java +
    - Modifier le javafx 
Les contraintes organisationnelles sont::
    - La version doit être livrée le 17 mai +
    - La répartition des rôles de l'équipe +
    - Gestion du git

Les différents livrables attendus sont::
    - Un fichier `jar` qui sera l'exécutable pour lancer l'application +
    - Un documentation technique à destination des développeurs pour permettre la maintenance de lapplication +
    - Une documentation utilisateurs à destinations des différents utisateurs de l'application pour comprendre son fonctionnement +
    - Un cahier de tests qui recouvrent différents tests du fonctionnement de l'application
